### ISSUE TITLE
Question About Pinner-Indexed

### ISSUE THREAD

**Issue by horsecarrot** [Iquaridys/Snurf-Corp#7]
Hello,

I was just wondering if you knew what the 'Pinner Indexed: true/false' means on the Pin information?

Thanks for your work, love the extension!

Michael.
![pinner-indexed](https://user-images.githubusercontent.com/48633588/78195910-5b810d00-74dd-11ea-91d9-6c9fd4e06816.jpg)

**Comment by Iquaridys** [comment]
Many pin show in pinterest feed with pinner index true,
if your account got pinner index false, i think not good to improve it. Better create another account.
