### ISSUE TITLE
Issue to send image

### ISSUE THREAD

**Issue by olaronymax** [Iquaridys/Snurf-Corp#9]
Hi, I have a problem sending images when I use number more. In certain countries the ninth digit ex 55 13 9 XXXX XXXX has been included when trying to send in this way does not work. However if it sends using 55 13 XXXX XXXX it works correctly.

**Comment by EveEHI789** [comment]
Hi, I have a problem sending images/files when I use number more. The file can't be attached. Will there be an application update?
